apiVersion: apps/v1
kind: Deployment
metadata:
  name: csd-metric-interface
  namespace: storage-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      name: csd-metric-interface
      namespace: storage-controller
  template:
    metadata:
      labels:
        name: csd-metric-interface
        namespace: storage-controller
    spec:
      nodeSelector:
        layer: storage
        type: csd
      serviceAccountName: csd-metric-interface
      imagePullSecrets:
        - name: regcred
      containers:
        - name: csd-metric-interface
          image: ketidevit2/csd-metric-interface:v0.0.1
          command:
          - csd-metric-interface
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OpenCSD_METRIC_COLLECTOR_IP
              value: "10.0.4.87"
            - name: OpenCSD_METRIC_COLLECTOR_PORT
              value: "30801"
            - name: OPERATOR_NAME
              value: "csd-metric-interface"
        - name: node-metric-collector
          image: ketidevit2/node-metric-collector:v0.0.1
          imagePullPolicy: Always
          env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: DEBUGG_LEVEL
            value: "LEVEL1"
          - name: NODE_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: OpenCSD_METRIC_COLLECTOR_IP
            value: "10.0.4.87"
          - name: OpenCSD_METRIC_COLLECTOR_PORT
            value: "30801"
      tolerations:
        - key: node.kubernetes.io/not-ready
          effect: NoExecute
          tolerationSeconds: 0
        - key: node.kubernetes.io/unreachable
          effect: NoExecute
          tolerationSeconds: 0
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: csd-metric-interface
  namespace: storage-controller
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csd-metric-interface
subjects:
- kind: ServiceAccount
  name: csd-metric-interface
  namespace: storage-controller
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Service
metadata:
  name: csd-metric-interface
  namespace: storage-controller
  labels:
    name: csd-metric-interface
    namespace: storage-controller
spec:
  type: NodePort
  ports:
  - name: csd-metric-interface
    port: 40800
    targetPort: 40800
    nodePort: 30004
    protocol: TCP
  - name: node-metric-collector
    port: 80
    targetPort: 8080
    nodePort: 32544
    protocol: TCP
  selector:
    name: csd-metric-interface
    namespace: storage-controller
