apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: csd-identifier
  name: csd-identifier
  namespace: storage-controller
spec:
  selector:
    matchLabels:
      app: csd-identifier
  template:
    metadata:
      labels:
        app: csd-identifier
      name: csd-identifier
    spec:
      nodeSelector:
        layer: storage
        type: csd
      imagePullSecrets:
        - name: regcred
      hostNetwork: true
      containers:
        - name: csd-identifier
          image: ketidevit2/csd-identifier:v1.0
          imagePullPolicy: Always
          volumeMounts:
            - name: tz-config
              mountPath: /etc/localtime
            - name: config
              mountPath: /root/.kube/  
          resources:
            limits:
              memory: "200Mi"
            requests:
              memory: "200Mi"
          env:
          - name: LOG_LEVEL
            value: "TRACE"
      volumes:
        - name: tz-config
          hostPath:
            path: /usr/share/zoneinfo/Asia/Seoul
        - name: config
          hostPath:
            path: /root/.kube
