apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: opencsd-storage-api-server
  namespace: storage-controller
spec:
  selector:
    matchLabels:
      name: opencsd-storage-api-server
  template:
    metadata:
      labels:
        name: opencsd-storage-api-server
        namespace: storage-controller
    spec:
      hostNetwork: true
      nodeSelector:
        layer: storage
      imagePullSecrets:
        - name: regcred
      containers:
        - name: opencsd-storage-api-server
          image: ketidevit2/opencsd-storage-api-server:v1.0
          command:
          - opencsd-storage-api-server
          imagePullPolicy: Always
          env:
            - name: INFLUXDB_DB
              value: opencsd_storage_metric_db
            - name: INFLUXDB_PASSWORD
              value: ketilinux
            - name: INFLUXDB_USER
              value: keti
            - name: INFLUXDB_PORT
              value: "8086"
          volumeMounts:
            - name: host-data
              mountPath: /mnt
      volumes:
      - name: host-data
        hostPath:
          path: /mnt
          type: Directory
      tolerations:
        - key: "use"
          operator: "Equal"
          value: "no"
          effect: "NoSchedule"
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: opencsd-storage-api-server-svc
#   namespace: storage-controller
# spec:
#   type: NodePort
#   selector:
#     name: opencsd-storage-api-server
#     namespace: storage-controller
#   ports:
#     - protocol: TCP
#       port: 40306  
#       targetPort: 40306 
#       nodePort: 30306  
#   externalTrafficPolicy: Local