apiVersion: apps/v1
kind: Deployment
metadata:
  name: opencsd-storage-manager
  namespace: storage-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      name: opencsd-storage-manager
      namespace: storage-controller
  template:
    metadata:
      labels:
        name: opencsd-storage-manager
        namespace: storage-controller
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: opencsd-storage-manager
          image: ketidevit2/opencsd-storage-manager:v0.0.1
          imagePullPolicy: Always
      nodeSelector:
        layer: storage
        type: csd
---
apiVersion: v1
kind: Service
metadata:
  name: opencsd-storage-manager
  namespace: storage-controller
  labels:
    name: opencsd-storage-manager
    namespace: storage-controller
spec:
  type: NodePort
  ports:
    - port: 40307
      targetPort: 40307
      nodePort: 30307
      protocol: TCP
  selector:
    name: opencsd-storage-manager
    namespace: storage-controller
